version: "2.1"


workflows:
  version: "2.1"

  non_master_pipeline:
    description: "Build and test. Applied to all non-master branches."
    filters:
      branches:
        ignore: master
    jobs:
      - build_verify
      - check_releasable_changes

  master_pipeline:
    description: "Build and test. Bump version and release, if manually approved."
    filters:
      branches:
        only: master
    jobs:
      - build_verify
      - check_releasable_changes
      - request_release:
          type: approval
          requires:
            - build_verify
            - check_releasable_changes
      - release:
          requires:
            - request_release


jobs:

  build_verify:
    description: "Build project and run all tests and checks."

    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
        # This is a public image (via Github Packages), so shouldn't need auth, but Github Packages does not yet
        # support authless read from public images
        # https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache deps
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}

      # Install deps
      - run:
          name: install dependencies
          command: |
            poetry --version
            poetry install --no-root

      # Save deps
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/project/.poetry/virtualenvs

      # Run all checks
      - run:
          name: run tests
          command: |
            poetry run verify-all

  check_releasable_changes:
    description: "Check if there are any releasable changes. Job will terminate if no releasable changes."
    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
    steps:
      - checkout
      - run:
          name: Show for releasable changes
          command: |
            result=$(poetry run find-releasable-changes)
            echo "${result}"
            if [[ ${result} == *"No changes to release"* ]]; then
              echo "Ending CircleCI job here"
              circleci-agent step halt
            fi

  release:
    description: "Release this version of the package to PyPI"
    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry run prepare-release
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_TOKEN}" --no-interaction
