version: "2.1"

orbs:
  codecov: codecov/codecov@1.0.5  # https://codecov.io/gh/mattjw/sparkql

workflows:
  version: "2.1"

  build_and_test_workflow:
    description: |
      Build and test on any non-master branch.
    jobs:
      - build_verify:
          filters:
            branches:
              ignore: master

  release_workflow:
    description: |
      Release all releasable changes, if any, on manual approval. Bump version and publish a release.
    jobs:
      - build_verify:
          filters:
            branches:
              only: master
      - request_release:
          type: approval
          requires:
            - build_verify
          filters:
            branches:
              only: master
      - release:
          requires:
            - build_verify
            - request_release
          filters:
            branches:
              only: master

jobs:

  build_verify:
    description: "Build the project and run all tests and checks."

    docker:
      - image: mattjwnet/circleci-python-java11:py3.10.1
          # https://hub.docker.com/r/mattjwnet/circleci-python-java11
        #auth:  #~
        #  username: ${GITHUB_USERNAME}
        #  password: ${GITHUB_DOCKER_READ_TOKEN}
        # This is a public image (via Github Packages), so shouldn't need auth, but Github Packages does not yet
        # support authless read from public images.
        # https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache deps
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}

      # Install deps
      - run:
          name: Install dependencies
          command: |
            poetry --version
            poetry install --no-root

      # Save deps
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/project/.poetry/virtualenvs

      # Run all checks
      - run:
          name: Run checks and tests
          command: |
            poetry run verify-all

      # Store/upload code coverage artifacts
      - store_artifacts:
          path: reports/htmlcov

      - store_artifacts:
          path: reports/coverage.xml

      - codecov/upload:
          # see https://codecov.io/gh/mattjw/sparkql
          file: reports/coverage.xml

      # Check for releasable changes (if any) (for convenience)
      - run:
          name: Check for releasable changes (if any)
          command: |
            poetry run find-releasable-changes


  release:
    # Notes...
    # - Requires a Github Personal Access Token as env var `GITHUB_WRITE_TOKEN`. Must have `repo` scope
    # - The PAT is treated as Administrator. Suggested master branch protection rules as follows:
    #     Require status checks to pass before merging = yes;
    #     Require branches to be up to date before merging = yes;
    #     Status checks = ci/circleci: build_verify (exclusively);
    #     Include administrators = no
    #   Exempting administrators will allow CircleCI (via the PAT) to push to master as part of a release.
    description: "Bump and release package to PyPI"
    docker:
      - image: ghcr.io/mattjw/docker-images/circleci-python-java11:py3.10.1
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            poetry --version
            poetry install --no-root
      - run:
          name: Ensure there are releasable changes
          command: |
            result=$(poetry run find-releasable-changes)
            echo "${result}"
            if [[ ${result} == *"No changes to release"* ]]; then
              echo "Ending CircleCI job here"
              circleci-agent step halt
            fi
      - run:
          name: Push to PyPI
          command: |
            poetry run prepare-release
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_TOKEN}" --no-interaction
