version: 2.1

jobs:

  build:
    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
        # This is a public image (via Github Packages), but Github Packages does not yet support
        # authless read from public images
        # https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache deps
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}

      # Install deps
      - run:
          name: install dependencies
          command: |
            poetry install --no-root

      # Save deps
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/project/.poetry/virtualenvs

      # Run all checks
      - run:
          name: run tests
          command: |
            poetry run verify-all
