version: "2.1"


workflows:
  version: "2.1"

  full_pipeline:
    description: "Complete project workflow: build, verify (test), release."
    jobs:
      #
      # Testing (all branches)
      - build_verify

      #
      # Release pipeline, with manual approval (master only)
      - check_releasable_changes:
          filters:
            branches:
              only: master
      - request_release:
          type: approval
          requires:
            - build_verify
            - check_releasable_changes
          filters:
            branches:
              only: master
      - release:
          requires:
            - request_release
          filters:
            branches:
              only: master


jobs:

  build_verify:
    description: "Build project and run all tests and checks"

    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
        # This is a public image (via Github Packages), so shouldn't need auth, but Github Packages does not yet
        # support authless read from public images
        # https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache deps
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}

      # Install deps
      - run:
          name: install dependencies
          command: |
            poetry --version
            poetry install --no-root

      # Save deps
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/project/.poetry/virtualenvs

      # Run all checks
      - run:
          name: run tests
          command: |
            poetry run verify-all

  check_releasable_changes:
    description: "Check if there are any releasable changes"
    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
    steps:
      - checkout
      - run:
          name: Show for releasable changes
          command: |
            poetry run releasable-changes

  release:
    description: "Release this version of the package to PyPI"
    docker:
      - image: docker.pkg.github.com/mattjw/docker-images/circleci-python-java8:py3.6.8
        auth:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_DOCKER_READ_TOKEN}
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_TOKEN}" --no-interaction
