# CI for all branches. Executes a build and verify (including testing, linting, and so on).

name: Continuous integration

on: [push, pull_request]

jobs:
  build_verify:

    runs-on: ubuntu-latest
    container:
      image: mattjwnet/python-poetry-java8:py3.6.8

    #strategy:
    #  matrix:
    #    python: [3.6, 3.7]

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Fetch all git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        # This is required for commitizen to operate quickly (see the
        # `find-releasable-changes` task)

      - name: Dependencies cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry --version
          poetry install --no-root

      - name: Run checks and tests
        run: |
          poetry run verify-all

      - name: Upload coverage artiface to Github
        # The artifact can be found in the Artifacts drop-down on the
        # Github page for the executed workflow
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: reports/htmlcov

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: reports/coverage.xml
          fail_ci_if_error: true

      - name: Check for releasable changes (if any)
        run: poetry run find-releasable-changes
